import { printToFileAsync } from "expo-print";
import { shareAsync } from "expo-sharing"; // FIX: shareAsync is from expo-sharing, not expo-print
import { CalculationInput, CalculationResult } from "../types";

export async function generateAndSharePDF(
  input: CalculationInput,
  result: CalculationResult,
) {
  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
          .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #0055A4; padding-bottom: 20px; }
          .title { font-size: 24px; font-weight: bold; color: #0055A4; }
          .subtitle { font-size: 14px; color: #666; margin-top: 5px; }
          .section { margin-bottom: 30px; }
          .section-title { font-size: 16px; font-weight: bold; color: #0055A4; margin-bottom: 15px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
          .row { display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 14px; }
          .row.bold { font-weight: bold; }
          .total-row { display: flex; justify-content: space-between; margin-top: 20px; padding-top: 15px; border-top: 2px solid #333; font-size: 18px; font-weight: bold; }
          .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #999; }
          .tag { background: #E6F4FE; color: #0055A4; padding: 2px 8px; border-radius: 4px; font-size: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">ImportEspana Estimate</div>
          <div class="subtitle">Official Car Import Cost Calculation</div>
          <div class="subtitle">${new Date().toLocaleDateString()}</div>
        </div>

        <div class="section">
          <div class="section-title">Vehicle Details</div>
          <div class="row"><span>Origin Country</span> <span>${input.originCountry}</span></div>
          <div class="row"><span>Factory Price (Purchase)</span> <span>${input.carPrice.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span></div>
          <div class="row"><span>Fiscal Value (Hacienda)</span> <span>${input.officialFiscalValue?.toLocaleString("de-DE", { style: "currency", currency: "EUR" }) || "N/A"}</span></div>
          <div class="row"><span>Age</span> <span>${input.carAge.replace(/_/g, " ")}</span></div>
          <div class="row"><span>CO2 Emissions</span> <span>${input.co2Emissions} g/km</span></div>
          <div class="row"><span>Depreciation (Official)</span> <span>${((1 - result.depreciationPercentage) * 100).toFixed(0)}%</span></div>
          <div class="row"><span>Tax Base</span> <span>${result.taxBase?.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span></div>
        </div>

        <div class="section">
          <div class="section-title">Tax Breakdown</div>
          <div class="row"><span>Matriculation Tax (${(result.taxRateApplied * 100).toFixed(2)}%)</span> <span>${result.registrationTax.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span></div>
          ${result.itpTax > 0 ? `<div class="row"><span>ITP (Transfer Tax)</span> <span>${result.itpTax.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span></div>` : ""}
          <div class="row"><span>Transport Cost</span> <span>${result.transportCost.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span></div>
          <div class="row"><span>DGT Fees</span> <span>${result.dgtFee.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span></div>
          <div class="row"><span>ITV Inspection</span> <span>${result.itvFee.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span></div>
          <div class="row"><span>Plates & Admin</span> <span>${result.platesFee.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span></div>
        </div>

        <div class="total-row">
          <span>TOTAL ESTIMATED COST</span>
          <span>${result.totalCost.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span>
        </div>
        
        <div style="text-align: right; margin-top: 10px; font-size: 12px; color: #666;">
          (Includes Car Price + All Taxes)
        </div>

        <div class="footer">
          <p>This is an estimate based on current Spanish regulations. Final costs may vary.<br>Generated by ImportEspana App.</p>
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await printToFileAsync({ html, base64: false });
    await shareAsync(uri, { UTI: ".pdf", mimeType: "application/pdf" });
  } catch (error) {
    console.error("Error generating PDF:", error);
  }
}
